package Kayttoliittyma;

import Logiikka.Etsija;
import Logiikka.Tallentaja;
import Logiikka.Poistaja;
import Logiikka.Lajittelija;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.text.Document;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;


public class Kayttoliittyma extends javax.swing.JFrame {

    private final Etsija etsija = new Etsija();
    private final Tallentaja talleta = new Tallentaja();
    private final Poistaja poistaja = new Poistaja();
    private Lajittelija lajittelija = null;
    private ArrayList<File> tiedostot;
    private boolean Shift = false;
    private boolean Enter = false;
    private String teksti;
    
    public Kayttoliittyma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogiLajittelu = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        NappiSelaa1 = new javax.swing.JButton();
        TekstikenttaMista = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NappiSelaa2 = new javax.swing.JButton();
        TekstikenttaMihin = new javax.swing.JTextField();
        NappiDialogiOK = new javax.swing.JButton();
        NappiDialogiPoistu = new javax.swing.JButton();
        CheckBoxSuosikit = new javax.swing.JCheckBox();
        CheckBoxDownloads = new javax.swing.JCheckBox();
        TiedostonValitsija = new javax.swing.JFileChooser();
        DialogiUudelleenNimea = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        NappulaDialogiUNselaa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TekstikenttaTiedostolista = new javax.swing.JTextArea();
        NappiDialogiUNok = new javax.swing.JButton();
        nappulaDialogiUNpoistu = new javax.swing.JButton();
        TekstikenttaDialogiUNuusinimi = new javax.swing.JTextField();
        RadioNappulaAlku = new javax.swing.JRadioButton();
        RadioNappulaLoppu = new javax.swing.JRadioButton();
        buttonGroupAlkuLoppu = new javax.swing.ButtonGroup();
        DialogiEtsi = new javax.swing.JDialog();
        EtsiTekstikentta = new javax.swing.JTextField();
        EtsiNappi = new javax.swing.JButton();
        NappiHae = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        NappiTalleta = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        NappiPoista = new javax.swing.JButton();
        NappiTyhjenna = new javax.swing.JButton();
        RadioNappulaHaenimia = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TekstikenttaPaa = new javax.swing.JTextPane();
        JLabeliRivit = new javax.swing.JLabel();
        Osumat = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuToiminnot = new javax.swing.JMenu();
        NappulaLajittele = new javax.swing.JMenuItem();
        MenuUudelleenNimea = new javax.swing.JMenuItem();
        MenuHaeTiedostosta = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mistä kansiosta?");

        NappiSelaa1.setText("Selaa...");
        NappiSelaa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappiSelaa1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mihin kansioon?");

        NappiSelaa2.setText("Selaa...");
        NappiSelaa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappiSelaa2ActionPerformed(evt);
            }
        });

        NappiDialogiOK.setText("OK");
        NappiDialogiOK.setEnabled(false);
        NappiDialogiOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappiDialogiOKActionPerformed(evt);
            }
        });

        NappiDialogiPoistu.setText("Poistu");
        NappiDialogiPoistu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappiDialogiPoistuActionPerformed(evt);
            }
        });

        CheckBoxSuosikit.setText("Suosikit");
        CheckBoxSuosikit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxSuosikitActionPerformed(evt);
            }
        });

        CheckBoxDownloads.setText("Lataukset");
        CheckBoxDownloads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxDownloadsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogiLajitteluLayout = new javax.swing.GroupLayout(DialogiLajittelu.getContentPane());
        DialogiLajittelu.getContentPane().setLayout(DialogiLajitteluLayout);
        DialogiLajitteluLayout.setHorizontalGroup(
            DialogiLajitteluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogiLajitteluLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogiLajitteluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(DialogiLajitteluLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NappiSelaa1))
                    .addGroup(DialogiLajitteluLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NappiSelaa2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogiLajitteluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TekstikenttaMihin, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(TekstikenttaMista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DialogiLajitteluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBoxSuosikit)
                    .addComponent(CheckBoxDownloads))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogiLajitteluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NappiDialogiPoistu)
                    .addComponent(NappiDialogiOK, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DialogiLajitteluLayout.setVerticalGroup(
            DialogiLajitteluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogiLajitteluLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogiLajitteluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NappiSelaa1)
                    .addComponent(TekstikenttaMista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NappiDialogiOK)
                    .addComponent(CheckBoxDownloads))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogiLajitteluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TekstikenttaMihin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NappiSelaa2)
                    .addComponent(NappiDialogiPoistu)
                    .addComponent(CheckBoxSuosikit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Valitse tiedostot");

        NappulaDialogiUNselaa.setText("Selaa...");
        NappulaDialogiUNselaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappulaDialogiUNselaaActionPerformed(evt);
            }
        });
        NappulaDialogiUNselaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NappiOkPaina(evt);
            }
        });

        TekstikenttaTiedostolista.setColumns(20);
        TekstikenttaTiedostolista.setRows(5);
        jScrollPane1.setViewportView(TekstikenttaTiedostolista);

        NappiDialogiUNok.setText("Ok");
        NappiDialogiUNok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappiDialogiUNokActionPerformed(evt);
            }
        });

        nappulaDialogiUNpoistu.setText("Poistu");
        nappulaDialogiUNpoistu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nappulaDialogiUNpoistuActionPerformed(evt);
            }
        });

        RadioNappulaAlku.setSelected(true);
        RadioNappulaAlku.setText("Alku");
        RadioNappulaAlku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioNappulaAlkuActionPerformed(evt);
            }
        });

        RadioNappulaLoppu.setText("Loppu");

        javax.swing.GroupLayout DialogiUudelleenNimeaLayout = new javax.swing.GroupLayout(DialogiUudelleenNimea.getContentPane());
        DialogiUudelleenNimea.getContentPane().setLayout(DialogiUudelleenNimeaLayout);
        DialogiUudelleenNimeaLayout.setHorizontalGroup(
            DialogiUudelleenNimeaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogiUudelleenNimeaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogiUudelleenNimeaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TekstikenttaDialogiUNuusinimi)
                    .addComponent(NappiDialogiUNok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(DialogiUudelleenNimeaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NappulaDialogiUNselaa)
                    .addComponent(RadioNappulaLoppu)
                    .addComponent(nappulaDialogiUNpoistu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioNappulaAlku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        DialogiUudelleenNimeaLayout.setVerticalGroup(
            DialogiUudelleenNimeaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogiUudelleenNimeaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogiUudelleenNimeaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogiUudelleenNimeaLayout.createSequentialGroup()
                        .addGroup(DialogiUudelleenNimeaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NappulaDialogiUNselaa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DialogiUudelleenNimeaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DialogiUudelleenNimeaLayout.createSequentialGroup()
                                .addComponent(RadioNappulaAlku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioNappulaLoppu))
                            .addGroup(DialogiUudelleenNimeaLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(TekstikenttaDialogiUNuusinimi)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DialogiUudelleenNimeaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nappulaDialogiUNpoistu)
                            .addComponent(NappiDialogiUNok)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        buttonGroupAlkuLoppu.add(RadioNappulaAlku);
        buttonGroupAlkuLoppu.add(RadioNappulaLoppu);

        EtsiTekstikentta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EtsiTekstikenttaKeyPressed(evt);
            }
        });

        EtsiNappi.setText("Etsi");
        EtsiNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtsiNappiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogiEtsiLayout = new javax.swing.GroupLayout(DialogiEtsi.getContentPane());
        DialogiEtsi.getContentPane().setLayout(DialogiEtsiLayout);
        DialogiEtsiLayout.setHorizontalGroup(
            DialogiEtsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogiEtsiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogiEtsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EtsiNappi, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(EtsiTekstikentta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DialogiEtsiLayout.setVerticalGroup(
            DialogiEtsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogiEtsiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtsiTekstikentta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EtsiNappi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NappiHae.setText("Hae");
        NappiHae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappiHaeActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NappainHae(evt);
            }
        });

        NappiTalleta.setText("Tallenna");
        NappiTalleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappiTalletaActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NappainTallenna(evt);
            }
        });

        NappiPoista.setText("Poista");
        NappiPoista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappiPoistaActionPerformed(evt);
            }
        });

        NappiTyhjenna.setText("Tyhjennä");
        NappiTyhjenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappiTyhjennaActionPerformed(evt);
            }
        });

        RadioNappulaHaenimia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RadioNappulaHaenimia.setText("Hae nimiä");
        RadioNappulaHaenimia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioNappulaHaenimiaActionPerformed(evt);
            }
        });

        TekstikenttaPaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TekstikenttaPaaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(TekstikenttaPaa);

        JLabeliRivit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Osumat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        MenuToiminnot.setText("Toiminnot");

        NappulaLajittele.setText("Lajittele");
        NappulaLajittele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappulaLajitteleActionPerformed(evt);
            }
        });
        MenuToiminnot.add(NappulaLajittele);

        MenuUudelleenNimea.setText("Uudelleen nimeä");
        MenuUudelleenNimea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUudelleenNimeaActionPerformed(evt);
            }
        });
        MenuToiminnot.add(MenuUudelleenNimea);

        MenuHaeTiedostosta.setText("Hae tiedostosta");
        MenuHaeTiedostosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHaeTiedostostaActionPerformed(evt);
            }
        });
        MenuToiminnot.add(MenuHaeTiedostosta);

        jMenuBar1.add(MenuToiminnot);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(NappiHae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioNappulaHaenimia)
                        .addGap(18, 18, 18)
                        .addComponent(NappiTalleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NappiPoista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NappiTyhjenna)
                        .addGap(18, 18, 18)
                        .addComponent(JLabeliRivit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Osumat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NappiHae)
                        .addComponent(NappiTalleta)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NappiPoista)
                        .addComponent(NappiTyhjenna)
                        .addComponent(RadioNappulaHaenimia))
                    .addComponent(JLabeliRivit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Osumat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        isActive();
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void NappiHaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappiHaeActionPerformed

        NappiTalleta.setEnabled(true);
        
        String hakusana = jTextField1.getText();       
        etsija.annaHakusana(hakusana);
        etsija.RadioNappula(RadioNappulaHaenimia.isSelected());
        System.out.println("radionappula: "+RadioNappulaHaenimia.isSelected()); //RADIONAPPULA PRINT
        teksti = etsija.avaaTiedosto();
        
        etsiTekstista(hakusana);
        
    }//GEN-LAST:event_NappiHaeActionPerformed

    private void NappainHae(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NappainHae

        if(evt.getKeyCode() == 10){
            etsija.nollaaRivit();
            NappiHae.doClick();
        }
    }//GEN-LAST:event_NappainHae

    private void etsiTekstista(String hakusana){
        int osumat = 0;
        Document dokumentti = TekstikenttaPaa.getDocument(); 
        StyleContext konteksti = new StyleContext();
        Style tyyli = konteksti.addStyle("korostus", null);
        StyleConstants.setForeground(tyyli, Color.red);
        Scanner lukija = new Scanner(teksti);
        
        if(teksti.equals("")){
            TekstikenttaPaa.setText("Ei tuloksia");
        }else{
            TekstikenttaPaa.setText("");
            while(lukija.hasNextLine()){
                String sana = lukija.nextLine();               
                if(sana.toLowerCase().contains(hakusana.toLowerCase())){
                    try{
                        dokumentti.insertString(dokumentti.getLength(), sana+"\n" , tyyli);
                        osumat++;
                    }catch(Exception e){
                        System.out.println(e);
                    }                 
                }else{
                    try{
                        dokumentti.insertString(dokumentti.getLength(), sana+"\n", null);
                    }catch(Exception e){
                        System.out.println(e);
                    }
                    
                }
            }
            if(etsija.getTiedostotluku() == 1 ){
                jTextField3.setText(etsija.getNimi());
            }else{
                jTextField3.setText("");
            }
            JLabeliRivit.setText(""+etsija.getRivit());
            lukija.close();
            Osumat.setText(""+osumat);
        }
    }
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        NappiTalleta.setEnabled(true);
        
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void NappiTalletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappiTalletaActionPerformed
        String nimi = jTextField3.getText();
        if(!nimi.equals("")){
            TekstikenttaPaa.select(0, 5);
            System.out.println(etsija.getPath());
            if(TekstikenttaPaa.getSelectedText().contains("C:\\")){
                TekstikenttaPaa.select(etsija.getPath().length()+2, TekstikenttaPaa.getText().length());               
                String teksti = TekstikenttaPaa.getSelectedText();
                System.out.println(talleta.Talleta(nimi, teksti)+" talleta");
                
            }else{
                TekstikenttaPaa.select(0, TekstikenttaPaa.getText().length());
                String teksti = TekstikenttaPaa.getSelectedText();
                System.out.println(talleta.Talleta(nimi, teksti)+" talleta");      
            }
            
        }if(nimi.equals("")){
            TekstikenttaPaa.setText("");
        }
    }//GEN-LAST:event_NappiTalletaActionPerformed

    private void NappainTallenna(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NappainTallenna
        
        if(evt.getKeyCode() == 10){
            NappiTalleta.doClick();
        }
        
    }//GEN-LAST:event_NappainTallenna

    private void NappiPoistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappiPoistaActionPerformed
        
        if(!jTextField3.getText().isEmpty()){
            int i = JOptionPane.showConfirmDialog(null, "Tahdotko poistaa tiedoston?", null, JOptionPane.YES_NO_OPTION);
            System.out.println(i+" poistaja");
            if(etsija.getTiedostotluku() == 1 && i == 0){
                System.out.println(poistaja.poistaTiedosto(jTextField3.getText()));
            }
        }
        
        
        
    }//GEN-LAST:event_NappiPoistaActionPerformed

    private void NappiTyhjennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappiTyhjennaActionPerformed
        TekstikenttaPaa.setText("");
        jTextField1.setText("");
        jTextField3.setText("");
        etsija.nollaaTiedostoluku();
    }//GEN-LAST:event_NappiTyhjennaActionPerformed

    private void NappiDialogiPoistuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappiDialogiPoistuActionPerformed
        DialogiLajittelu.setVisible(false);
        DialogiLajittelu.dispose();
    }//GEN-LAST:event_NappiDialogiPoistuActionPerformed

    private void NappiDialogiOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappiDialogiOKActionPerformed
        String mista = TekstikenttaMista.getText();
        if(CheckBoxSuosikit.isSelected()){
            TekstikenttaMihin.setText("C:\\Users\\Jouni\\Desktop\\Kansiot\\Kuvat\\Pron\\Mallit");
        }
        String minne = TekstikenttaMihin.getText();
        lajittelija = new Lajittelija(mista,minne);
        DialogiLajittelu.setVisible(false);
        DialogiLajittelu.dispose();
        TekstikenttaPaa.setText("Tiedostoja siirretty: "+lajittelija.getSiirretytLkm()+".\ntiedostojen nimet:\n");
        ArrayList<String> lista = new ArrayList<>(lajittelija.getTiedostojenNimet());
        for(String i : lista){
            try{
                Document dokumentti = TekstikenttaPaa.getDocument();
                dokumentti.insertString(dokumentti.getLength(), i+"\n", null);
            }catch(Exception e){
                System.out.println(e);
            }
            
        }
        
        NappiTalleta.setEnabled(false);
    }//GEN-LAST:event_NappiDialogiOKActionPerformed

    private void NappiSelaa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappiSelaa1ActionPerformed
        TiedostonValitsija.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        int vastaus = TiedostonValitsija.showOpenDialog(this);
        try{
            TekstikenttaMista.setText(""+TiedostonValitsija.getSelectedFile().getPath());
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_NappiSelaa1ActionPerformed

    private void NappiSelaa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappiSelaa2ActionPerformed
        TekstikenttaMihin.setText("");
        TiedostonValitsija.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        int vastaus = TiedostonValitsija.showOpenDialog(this);
        try{
            TekstikenttaMihin.setText(""+TiedostonValitsija.getSelectedFile().getPath());
        }catch(Exception e){
            System.out.println(e);
        }
        
        NappiDialogiOK.setEnabled(true);
    }//GEN-LAST:event_NappiSelaa2ActionPerformed

    private void RadioNappulaHaenimiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioNappulaHaenimiaActionPerformed
        
    }//GEN-LAST:event_RadioNappulaHaenimiaActionPerformed

    private void CheckBoxSuosikitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxSuosikitActionPerformed
        NappiDialogiOK.setEnabled(true);
        if(!CheckBoxSuosikit.isSelected()){
            TekstikenttaMihin.setText("");
            NappiDialogiOK.setEnabled(false);
        }if(CheckBoxSuosikit.isSelected()){
            TekstikenttaMihin.setText("C:\\Users\\Jouni\\Desktop\\Kansiot\\Kuvat\\Pron\\Mallit");
        }     
    }//GEN-LAST:event_CheckBoxSuosikitActionPerformed

    private void NappulaLajitteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappulaLajitteleActionPerformed
        DialogiLajittelu.pack();
        DialogiLajittelu.setVisible(true);
    }//GEN-LAST:event_NappulaLajitteleActionPerformed

    private void MenuUudelleenNimeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUudelleenNimeaActionPerformed
        DialogiUudelleenNimea.pack();
        TekstikenttaDialogiUNuusinimi.setText("");
        TekstikenttaTiedostolista.setText("");
        DialogiUudelleenNimea.setVisible(true);
    }//GEN-LAST:event_MenuUudelleenNimeaActionPerformed

    private void RadioNappulaAlkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioNappulaAlkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioNappulaAlkuActionPerformed

    private void NappulaDialogiUNselaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappulaDialogiUNselaaActionPerformed
        TiedostonValitsija.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
        TiedostonValitsija.setMultiSelectionEnabled(true);
        TiedostonValitsija.showOpenDialog(this);
        
        tiedostot = new ArrayList<File>();
        
        if(TiedostonValitsija.getSelectedFiles() != null){
            for(File i : TiedostonValitsija.getSelectedFiles()){
                TekstikenttaTiedostolista.setText(TekstikenttaTiedostolista.getText() + i.getName() + "\n");
                tiedostot.add(i);
            }
        }
        
        
    }//GEN-LAST:event_NappulaDialogiUNselaaActionPerformed

    private void nappulaDialogiUNpoistuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nappulaDialogiUNpoistuActionPerformed
        tiedostot.clear();
        DialogiUudelleenNimea.setVisible(false);
        DialogiUudelleenNimea.dispose();
    }//GEN-LAST:event_nappulaDialogiUNpoistuActionPerformed

    private void NappiDialogiUNokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappiDialogiUNokActionPerformed
        DialogiUudelleenNimea.setVisible(false);
        DialogiUudelleenNimea.dispose();   
        
        try{
        if(RadioNappulaAlku.isSelected() && !TekstikenttaDialogiUNuusinimi.getText().equals("")){
            for(File i : tiedostot){
                File file = new File(i.getParent()+"\\"+TekstikenttaDialogiUNuusinimi.getText()+i.getName());
                i.renameTo(file);
            }
            JOptionPane.showMessageDialog(null, "Tiedostojen nimeäminen onnistui, tiedostoja nimetty "+tiedostot.size(), null, JOptionPane.INFORMATION_MESSAGE);
        }
        if(RadioNappulaLoppu.isSelected() && !TekstikenttaDialogiUNuusinimi.getText().equals("")){
            for(File i : tiedostot){
                File file = new File(i.getParent()+"\\"+i.getName().substring(0,i.getName().length()-4)+TekstikenttaDialogiUNuusinimi.getText()+i.getName().substring(i.getName().length()-4,i.getName().length()));
                i.renameTo(file);       
            }
            JOptionPane.showMessageDialog(null, "Tiedostojen nimeäminen onnistui, tiedostoja nimetty "+tiedostot.size(), null, JOptionPane.INFORMATION_MESSAGE);
        }
        }catch(Exception e){
            System.out.println(e);
            TekstikenttaPaa.setText("Tiedostojen nimeäminen epäonnistui");
        }
        TekstikenttaDialogiUNuusinimi.setText("");
        TekstikenttaTiedostolista.setText("");                     
    }//GEN-LAST:event_NappiDialogiUNokActionPerformed

    private void NappiOkPaina(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NappiOkPaina

        if(evt.getKeyCode() == 10){
            NappiDialogiOK.doClick();
        }
    }//GEN-LAST:event_NappiOkPaina

    private void CheckBoxDownloadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxDownloadsActionPerformed
        if(CheckBoxDownloads.isSelected()){
            TekstikenttaMista.setText("C:\\Users\\Jouni\\Downloads");
        }else{
            TekstikenttaMista.setText("");
        }
    }//GEN-LAST:event_CheckBoxDownloadsActionPerformed

    private void TekstikenttaPaaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TekstikenttaPaaKeyPressed

    }//GEN-LAST:event_TekstikenttaPaaKeyPressed

    private void MenuHaeTiedostostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHaeTiedostostaActionPerformed
        DialogiEtsi.pack();
        DialogiEtsi.setVisible(true);
    }//GEN-LAST:event_MenuHaeTiedostostaActionPerformed

    private void EtsiNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtsiNappiActionPerformed
        if(EtsiTekstikentta.getText() != null && teksti != null){
            etsiTekstista(EtsiTekstikentta.getText());
        }else{
            TekstikenttaPaa.setText("Ei avonaista tiedostoa!");
        }
    }//GEN-LAST:event_EtsiNappiActionPerformed

    private void EtsiTekstikenttaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EtsiTekstikenttaKeyPressed
        if(evt.getKeyChar() == evt.VK_ENTER){
            EtsiNappi.doClick();
        }
    }//GEN-LAST:event_EtsiTekstikenttaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayttoliittyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayttoliittyma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxDownloads;
    private javax.swing.JCheckBox CheckBoxSuosikit;
    private javax.swing.JDialog DialogiEtsi;
    private javax.swing.JDialog DialogiLajittelu;
    private javax.swing.JDialog DialogiUudelleenNimea;
    private javax.swing.JButton EtsiNappi;
    private javax.swing.JTextField EtsiTekstikentta;
    private javax.swing.JLabel JLabeliRivit;
    private javax.swing.JMenuItem MenuHaeTiedostosta;
    private javax.swing.JMenu MenuToiminnot;
    private javax.swing.JMenuItem MenuUudelleenNimea;
    private javax.swing.JButton NappiDialogiOK;
    private javax.swing.JButton NappiDialogiPoistu;
    private javax.swing.JButton NappiDialogiUNok;
    private javax.swing.JButton NappiHae;
    private javax.swing.JButton NappiPoista;
    private javax.swing.JButton NappiSelaa1;
    private javax.swing.JButton NappiSelaa2;
    private javax.swing.JButton NappiTalleta;
    private javax.swing.JButton NappiTyhjenna;
    private javax.swing.JButton NappulaDialogiUNselaa;
    private javax.swing.JMenuItem NappulaLajittele;
    private javax.swing.JLabel Osumat;
    private javax.swing.JRadioButton RadioNappulaAlku;
    private javax.swing.JRadioButton RadioNappulaHaenimia;
    private javax.swing.JRadioButton RadioNappulaLoppu;
    private javax.swing.JTextField TekstikenttaDialogiUNuusinimi;
    private javax.swing.JTextField TekstikenttaMihin;
    private javax.swing.JTextField TekstikenttaMista;
    private javax.swing.JTextPane TekstikenttaPaa;
    private javax.swing.JTextArea TekstikenttaTiedostolista;
    private javax.swing.JFileChooser TiedostonValitsija;
    private javax.swing.ButtonGroup buttonGroupAlkuLoppu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton nappulaDialogiUNpoistu;
    // End of variables declaration//GEN-END:variables

}
